### ISSUE TITLE
[BUG] .circleci/config.yml and src/* do not align 

### ISSUE THREAD

**Issue by timothyclarke** [CircleCI-Public/orb-tools-orb#120]
I'm looking to use some elements of this repo as reference for other orbs. 
I assume (perhaps falsely) that `src/*` is being packed to `.circleci/config.yml` eg `circleci config pack src > .circleci/config.yml` however the content of `.circleci/config.yml` does not match the content of `src`. 

As one example `.circleci/config.yml` has a [test-commands](https://github.com/CircleCI-Public/orb-tools-orb/blob/master/.circleci/config.yml#L58-L81) job but there is no `test-commands.yml` in https://github.com/CircleCI-Public/orb-tools-orb/tree/master/src/jobs

**Comment by KyleTryon** [comment]
Hello @timothyclarke,

This repo uses specific code that many orbs will not use or need due to this orb being dependent on itself.

The orb template project is where the example template is housed https://github.com/CircleCI-Public/Orb-Project-Template

After Orb tools 11 is published #111 we will be using: https://github.com/CircleCI-Public/Orb-Template
