### ISSUE TITLE
Issues with Local Usage

### ISSUE THREAD

**Issue by jgiovaresco** [CircleCI-Public/orb-tools-orb#135]
## Orb version:
v11.1.2

## What happened:

Running commands described [here](https://github.com/CircleCI-Public/orb-tools-orb#local-usage) leads to error:

Example:

```
❯ circleci local execute --job orb-tools/review
Error: Error calling workflow: 'lint-pack'
Error calling job: 'orb-tools-alpha/continue'
Type error for argument pipeline-number: expected type: integer, actual value: "1" (type string)
```

```
❯ circleci config validate
Error: Error calling workflow: 'lint-pack'
Error calling job: 'orb-tools-alpha/continue'
Type error for argument pipeline-number: expected type: integer, actual value: "1" (type string)
```

## Expected behavior:

I think all the jobs of the project should be executable locally, except maybe the publish and continue

## Additional Information:

I suppose it is due to a default value given for [pipeline-number](https://github.com/CircleCI-Public/orb-tools-orb/blob/master/src/jobs/continue.yml#L8) parameter. 
Maybe we could change it type for `string` as it seems to be only used to build the URL of the parent pipeline: https://github.com/CircleCI-Public/orb-tools-orb/blob/master/src/scripts/continue.sh#L40

**Comment by KyleTryon** [comment]
It is fixed-ish!

There are still unfortunately some other gotchays involved so far it seems. 

1. The `.yamllint` file is seemingly not being respected when ran via the local execute command.
2. The review job now uploads tests results as JUNIT XML to the test results service on CircleCI. Because of this, the review job still does not function fully locally. Because we could not showcase both Junit format and a text based format at the same time, we opted to use Junit. Unfortunately this means the review job will only work on CircleCI.com for the time being. I have removed it from our docs. I would like to continue to modify/improve the review job to potentially show the text based results locally, based on the presence of the `ci` variable.
