### ISSUE TITLE
trigger-integration-workflow's cleanup-tags option only cleans up hardcoded tags

### ISSUE THREAD

**Issue by jrnail23** [CircleCI-Public/orb-tools-orb#41]
### Orb version
v1.27.1

### What happened
When running `trigger-integration-workflow` with `cleanup-tags: true` and with a non-default `tag` param  (i.e., `tag: custom_tag`), my previous `custom_tag-*` tags don't get cleaned up.

### Expected behavior
I expect my previous tags that match my `tag` param to be deleted.

### Other comments
I noticed this in the `trigger-integration-workflow` [source](https://github.com/jrnail23/orb-tools-orb/blob/master/src/jobs/trigger-integration-workflow.yml#L131):
```sh
# delete local tags
git tag -d $(git tag -l "integration-*")
git tag -d $(git tag -l "master-skip-master-*")
# fetch remote tags
git fetch
# delete remote tags
git push origin --delete $(git tag -l "integration-*") || true
git push origin --delete $(git tag -l "master-skip-master-*") || true # pushing once should be faster than multiple timesshould be faster than multiple times
```

and it seems that
```sh
$(git tag -l "integration-*")
```
should probably be changed to
```sh
$(git tag -l "<<parameters.tag>>-*")
```

However, I'm not sure what to do about `$(git tag -l "master-skip-master-*")` though.

**Comment by iynere** [comment]
@jrnail23 you mean `8.27.1` for version, right ?

some context here: previously, the `tag` parameter was `type: enum`, with the only options being `integration` or `master`. we changed it to a string as a user request:

https://github.com/CircleCI-Public/orb-tools-orb/pull/37

so that folks could push any tag. i'm not sure if the `cleanup-tags` param can / should be modified, as well ? it's designed to serve a very specific purpose

the idea is that you don't want to delete tags that resulted in a production orb release, which are only triggered by tags that fit the form `master-$RELEASE-master`, where `RELEASE` is `patch`, `minor`, or `major`. changing that pattern would involve a deeper set of changes to not just this command, but others as well.

that said, changing `$(git tag -l "integration-*")` to `$(git tag -l "<<parameters.tag>>-*")` is an easy partial fix, if you want to submit a PR.

& you can always run a `post-step` & specify your own custom tag-cleanup logic:

https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps

**Comment by jrnail23** [comment]
@iynere, thanks for the quick reply.  That makes sense to me... I should have a PR up for that partial fix within the hour.
